// details
export const FETCH_MULTIPLE_PACKAGES_DETAILS = 'FETCH_MULTIPLE_PACKAGES_DETAILS';
export const START_MULTIPLE_PACKAGES_DETAILS = 'START_MULTIPLE_PACKAGES_DETAILS';
export const UPDATE_PACKAGE_DETAILS = 'UPDATE_PACKAGE_DETAILS';
export const ERROR_PACKAGE_DETAILS = 'ERROR_PACKAGE_DETAILS';

// router
export const REDIRECT_TO_PAGE = 'REDIRECT_TO_PAGE';
export const END_OF_REDIRECT = 'END_OF_REDIRECT';
